# Standard parameters for the module
class syslog_ng::params {
  $bad_hostname                     = 'no'
  $chain_hostnames                  = 'no'
  $check_hostname                   = 'no'
  $config_dir                       = '/etc/syslog-ng/conf.d'
  $create_dirs                      = 'no'
  $custom_domain                    = ''
  $dir_group                        = 'adm'
  $dir_owner                        = 'root'
  $dir_perm                         = '0700'
  $dns_cache                        = 'yes'
  $dns_cache_expire                 = '3600'
  $dns_cache_expire_failed          = '60'
  $dns_cache_hosts                  = 'undef'
  $dns_cache_size                   = undef
  $file_template                    = '1007'
  $flush_lines                      = '0'
  $frac_digits                      = '0'
  $group                            = 'adm'
  $keep_hostname                    = 'no'
  $keep_timestamp                   = 'yes'
  $local_source                     = 's_src'
  $log_fifo_size                    = '10000'
  $log_fifo_size_destination        = '1000'
  $log_msg_size                     = '8192'
  $logstore_journal_shmem_threshold = '536870912'
  $mark_freq                        = '1200'
  $normalize_hostnames              = 'no'
  $on_error                         = 'drop-message'
  $owner                            = 'root'
  $perm                             = '0640'
  $reminder_file                    = undef
  $stats_freq                       = '600'
  $stats_level                      = '0'
  $system_log_dir                   = '/var/log'
  $threaded                         = 'no'
  $time_reap                        = '60'
  $time_reopen                      = '60'
  $timestamp_freq                   = '0'
  $timestamp_policy                 = undef
  $timestamp_url                    = undef
  $ts_format                        = 'rfc3164'
  $use_dns                          = 'yes'
  $use_fqdn                         = 'no'
  $use_uniqid                       = 'no'

  # Config file fragments
  $config_file_sources              = "${config_dir}/10sources.conf"
  $config_file_destination_files    = "${config_dir}/20destination_files.conf"
  $config_file_destination_fallback = "${config_dir}/20destination_fallback.conf"
  $config_file_destination_remote   = "${config_dir}/20destination_remote.conf"
  $config_file_filter               = "${config_dir}/30filter.conf"
  $config_file_parser               = "${config_dir}/40parser.conf"
  $config_file_rewrite              = "${config_dir}/50rewrite.conf"
  $config_file_logging              = "${config_dir}/90logging.conf"
  $config_file_fallback             = "${config_dir}/99fallback.conf"
}
